#!/usr/bin/env python

import numpy as np
import os
from pathlib import Path

# Read config file
fp = Path(sys.argv[0]).parent.resolve() / "config.json"
if not fp.is_file():
    logging.critical(f"ERROR: Configuration file {fp} not found")
    sys.exit(1)
with open(fp, "r") as fh:
    global config
    config = json.load(fh)
assert(type(config)==dict)

overlay_color = config["overlay_color"]
surface_color = config["surface_color"]
interval = config["interval"]

# Internals
format_pc = lambda x: f"{x:.1f}"
format_class = lambda x: f"{x:.0f}"
outfp = Path(sys.argv[0]).parent.resolve() / "mediaplayer-progressbar.css"
print(f"Writing output to {outfp}")

outfh = open(outfp, "w", encoding="utf8")

for i in np.arange(0, 100+interval, interval):
    class_ = format_class(i).replace(".", "-")
    i2 = i + (interval / 10)
    outfh.write(
f"""#custom-mediaplayer.{class_} {{
    background-image: linear-gradient(
    to right,
    {overlay_color} {format_pc(i)}%,
    {surface_color} {format_pc(i2)}%
    );
}}\n"""
    )

outfh.close()
